export enum Profile {
  FULLSTACK_DEVELOPER   = 'FULLSTACK_DEVELOPER',
  FRONTEND_DEVELOPER    = 'FRONTEND_DEVELOPER',
  BACKEND_DEVELOPER     = 'BACKEND_DEVELOPER',
  MOBILE_DEVELOPER      = 'MOBILE_DEVELOPER',
  DEVOPS                = 'DEVOPS',
  DATA_SCIENCE          = 'DATA_SCIENCE',
  MACHINE_LEARNING      = 'MACHINE_LEARNING',
  QA                    = 'QA',
  PROJECT_MANAGER       = 'PROJECT_MANAGER',
  PRODUCT_MANAGER       = 'PRODUCT_MANAGER',
  DESIGNER              = 'DESIGNER',
  ACCOUNTANT            = 'ACCOUNTANT',
  HR                    = 'HR',
  MARKETING             = 'MARKETING',
  SALES                 = 'SALES',
  CUSTOMER_SUPPORT      = 'CUSTOMER_SUPPORT',
  OTHER                 = 'OTHER'
}
